name: Override descriptions

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'descriptions.yml'
      - 'adminapi.json'

jobs:
  run-override:
    uses: shopware/docs-ci/.github/workflows/apply_overrides.yml@main
    with:
      override_file: descriptions.yml
      schema_file: adminapi.json
    secrets: inherit

  overrideDescriptions:
    name: "Finalize adminapi.json"
    runs-on: ubuntu-latest
    needs: [run-override]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: download api schema
        uses: actions/download-artifact@v3
        with:
          name: storeapi.json
      
      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          add-paths: adminapi.json
          author: shopwareBot <example@example.com>
          committer: shopwareBot <example@example.com>
          assignees: elkmod, Christian-Rades
          branch: schema-update
          delete-branch: true
          title: 'Add descriptions'

