name: Schedule version PRs

on:
  push

jobs:
  get-latest-version:
    name: "Get latest version"
    runs-on: ubuntu-latest
    steps:
      - name: Call github API
        id: latest-shopware-version
        run: |
          echo latest_version=$(curl -s https://api.github.com/repos/shopware/shopware/releases/latest | jq -r '.tag_name') >> $GITHUB_OUTPUT
    outputs:
      latest_version: ${{ steps.latest-shopware-version.outputs.latest_version }}
    
    
  generate-trunk:
    uses: ./.github/workflows/base_schema.yml@main
    with:
      shopware_version: 'trunk'
    secrets: inherit
    
  generate-latest:
    needs: get-latest-version
    uses: ./.github/workflows/base_schema.yml@latest
    with:
      shopware_version: ${{needs.get-latest-version.outputs.latest_version}}
    secrets: inherit
